services:
  db:
    image: postgres:16-alpine
    container_name: liter-alura-one-challenge-db
    restart: always
    environment:
      POSTGRES_DB: liter-alura-one-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: